
import {
  AlertTriangle, 
  Brain, 
  Code, 
  Globe, 
  Lock,
  MessagesSquare, 
  Bot, 
  ShieldAlert, 
  Sparkles, 
  Tv,
  Bitcoin,
  DollarSign,
  BadgeDollarSign,
  BadgeCheck,
  Camera,
  Network,
  Wand,
  Headphones,
  Video,
  Monitor,
  Settings,
  Search,
  MessageSquare,
  FileText,
  Music,
  Image
} from "lucide-react";
import { Extension } from "./extensionsData";

// Create beta extensions with the same interface as regular extensions
export const betaExtensionsData: Extension[] = [
  {
    id: 101, // Use IDs that won't conflict with regular extensions
    name: "AI Content Detector",
    description: "Advanced algorithm to detect AI-generated content across websites with high accuracy.",
    category: "AI",
    rating: 4.8,
    users: 12500,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.1",
    icon: Brain,
    iconBg: "bg-gradient-to-br from-indigo-500 to-indigo-700",
    isBeta: true, // Mark as beta extension
    estimatedRelease: "June 2025"
  },
  {
    id: 102,
    name: "Privacy Guardian Pro",
    description: "Next-generation privacy protection with advanced tracker blocking and fingerprint masking.",
    category: "Privacy & Security",
    rating: 4.7,
    users: 10800,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.8.5",
    icon: ShieldAlert,
    iconBg: "bg-gradient-to-br from-red-500 to-red-700",
    isBeta: true,
    estimatedRelease: "July 2025"
  },
  {
    id: 103,
    name: "Multilingual Assistant",
    description: "Real-time webpage translation in 50+ languages with contextual understanding.",
    category: "Productivity",
    rating: 4.5,
    users: 8900,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.7.2",
    icon: Globe,
    iconBg: "bg-gradient-to-br from-green-500 to-green-700",
    isBeta: true,
    estimatedRelease: "August 2025"
  },
  {
    id: 104,
    name: "Code Inspector",
    description: "Analyze and optimize JavaScript, CSS, and HTML in real-time while browsing.",
    category: "Developer Tools",
    rating: 4.9,
    users: 14500,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.4",
    icon: Code,
    iconBg: "bg-gradient-to-br from-blue-500 to-blue-700",
    isBeta: true,
    estimatedRelease: "June 2025"
  },
  {
    id: 105,
    name: "Quantum VPN",
    description: "Built-in VPN service with quantum-resistant encryption protocols.",
    category: "Privacy & Security",
    rating: 4.6,
    users: 11200,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.8.1",
    icon: Lock,
    iconBg: "bg-gradient-to-br from-purple-500 to-purple-700",
    isBeta: true,
    estimatedRelease: "September 2025"
  },
  {
    id: 106,
    name: "Smart Screen Reader",
    description: "Advanced screen reader with natural language processing for better accessibility.",
    category: "Accessibility",
    rating: 4.7,
    users: 9800,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.8.7",
    icon: Tv,
    iconBg: "bg-gradient-to-br from-yellow-500 to-yellow-700",
    isBeta: true,
    estimatedRelease: "July 2025"
  },
  {
    id: 107,
    name: "Web3 Navigator",
    description: "Seamless integration with blockchain apps and decentralized services.",
    category: "Web3 & Crypto",
    rating: 4.8,
    users: 13200,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.2",
    icon: Sparkles,
    iconBg: "bg-gradient-to-br from-orange-500 to-orange-700",
    isBeta: true,
    estimatedRelease: "August 2025"
  },
  {
    id: 108,
    name: "AI Chat Companion",
    description: "Context-aware chatbot that helps with research and online tasks.",
    category: "AI",
    rating: 4.6,
    users: 10500,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.8.3",
    icon: MessagesSquare,
    iconBg: "bg-gradient-to-br from-pink-500 to-pink-700",
    isBeta: true,
    estimatedRelease: "October 2025"
  },
  {
    id: 109,
    name: "Automated Tester",
    description: "Run accessibility, performance, and security tests on any webpage instantly.",
    category: "Developer Tools",
    rating: 4.5,
    users: 8700,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.7.8",
    icon: Bot,
    iconBg: "bg-gradient-to-br from-teal-500 to-teal-700",
    isBeta: true,
    estimatedRelease: "September 2025"
  },
  {
    id: 110,
    name: "Vulnerability Scanner",
    description: "Real-time detection of security vulnerabilities, phishing attempts, and malicious code.",
    category: "Privacy & Security",
    rating: 4.7,
    users: 12100,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.8.9",
    icon: AlertTriangle,
    iconBg: "bg-gradient-to-br from-amber-500 to-amber-700",
    isBeta: true,
    estimatedRelease: "November 2025"
  },
  {
    id: 111,
    name: "CryptoTracker Pro",
    description: "Advanced real-time cryptocurrency tracking with price alerts, portfolio analytics and market predictions.",
    category: "Web3 & Crypto",
    rating: 4.9,
    users: 15800,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.5",
    icon: Bitcoin,
    iconBg: "bg-gradient-to-br from-amber-500 to-amber-700",
    isBeta: true,
    estimatedRelease: "June 2025"
  },
  {
    id: 112,
    name: "Blockchain Explorer",
    description: "Browse and analyze blockchain transactions, smart contracts, and token data with professional-grade tools.",
    category: "Web3 & Crypto",
    rating: 4.8,
    users: 13200,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.1",
    icon: BadgeCheck,
    iconBg: "bg-gradient-to-br from-purple-500 to-purple-700",
    isBeta: true,
    estimatedRelease: "July 2025"
  },
  // Include several representative extensions from each category in ConceptualExtensions.tsx
  {
    id: 113,
    name: "AIWriter Pro",
    description: "Advanced AI writing assistant that enhances your writing with context-aware suggestions, tone adjustments, and document generation.",
    category: "AI",
    rating: 4.9,
    users: 14800,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.8",
    icon: Bot,
    iconBg: "bg-gradient-to-br from-indigo-500 to-indigo-700",
    isBeta: true,
    estimatedRelease: "June 2025"
  },
  {
    id: 114,
    name: "ImageGenius",
    description: "Generate custom images from text descriptions with fine-tuned style controls and advanced editing capabilities right in your browser.",
    category: "AI",
    rating: 4.8,
    users: 13500,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.8.6",
    icon: Image,
    iconBg: "bg-gradient-to-br from-pink-500 to-pink-700",
    isBeta: true,
    estimatedRelease: "July 2025"
  },
  {
    id: 115,
    name: "PhotoEnhancer",
    description: "AI-powered photo editing tool that automatically enhances images, removes unwanted elements, and applies professional-grade effects.",
    category: "Media",
    rating: 4.8,
    users: 12300,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.2",
    icon: Camera,
    iconBg: "bg-gradient-to-br from-orange-500 to-orange-700",
    isBeta: true,
    estimatedRelease: "July 2025"
  },
  {
    id: 116,
    name: "VoiceGenius",
    description: "Convert text to natural-sounding speech in 40+ languages with customizable voices, emotions, and accents for content creation.",
    category: "Communications",
    rating: 4.9,
    users: 14200,
    installed: false,
    enabled: false,
    featured: false,
    version: "0.9.7",
    icon: Headphones,
    iconBg: "bg-gradient-to-br from-purple-500 to-purple-700",
    isBeta: true,
    estimatedRelease: "June 2025"
  }
];
