import { 
  Shield, 
  Lock, 
  Search, 
  Download, 
  Zap, 
  Eye, 
  Code, 
  FileCode, 
  UserRound, 
  Clock, 
  CreditCard, 
  Bookmark,
  Image, 
  Send, 
  Mail, 
  Layers, 
  PieChart, 
  Languages, 
  Scissors,
  VolumeX, 
  Lightbulb, 
  Sparkles, 
  Github, 
  CloudRain, 
  Newspaper,
  FileText, 
  Sunrise, 
  ShoppingBag, 
  Wallet, 
  BellRing, 
  Link,
  Fingerprint, 
  BarChart4, 
  Share2, 
  Settings, 
  KeyRound, 
  LucideIcon  
} from "lucide-react";

export interface Extension {
  id: number;
  name: string;
  description: string;
  category: string;
  rating: number;
  users: number;
  installed: boolean;
  enabled: boolean;
  featured: boolean;
  version: string;
  icon: LucideIcon;
  iconBg: string;
}

const iconBackgrounds = [
  "bg-gradient-to-br from-purple-500 to-purple-700",
  "bg-gradient-to-br from-blue-500 to-blue-700",
  "bg-gradient-to-br from-pink-500 to-pink-700",
  "bg-gradient-to-br from-emerald-500 to-emerald-700",
  "bg-gradient-to-br from-amber-500 to-amber-700",
  "bg-gradient-to-br from-sky-500 to-sky-700",
  "bg-gradient-to-br from-rose-500 to-rose-700",
  "bg-gradient-to-br from-indigo-500 to-indigo-700",
];

export const extensionsData: Extension[] = [
  // Privacy & Security
  {
    id: 1,
    name: "NexusShield",
    description: "Comprehensive ad blocker and privacy protector that blocks trackers, cookies, and unwanted ads across all websites.",
    category: "Privacy & Security",
    rating: 4.9,
    users: 2547823,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.3.1",
    icon: Shield,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 2,
    name: "PrivatePass",
    description: "Advanced password manager that securely stores your passwords with military-grade encryption and auto-fills login forms.",
    category: "Privacy & Security",
    rating: 4.8,
    users: 1824596,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.1.0",
    icon: Lock,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 3,
    name: "ThreatDefender",
    description: "Detects and blocks malicious websites, phishing attempts, and potentially harmful downloads in real-time.",
    category: "Privacy & Security",
    rating: 4.7,
    users: 965321,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.9.2",
    icon: Shield,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 4,
    name: "BiometricGuard",
    description: "Adds fingerprint and facial recognition support for website logins, enhancing security while simplifying the authentication process.",
    category: "Privacy & Security",
    rating: 4.6,
    users: 542987,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.0.5",
    icon: Fingerprint,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 5,
    name: "DataVault",
    description: "Local encryption for sensitive information like credit cards and personal data with secure access via master password.",
    category: "Privacy & Security",
    rating: 4.5,
    users: 387451,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.7.3",
    icon: KeyRound,
    iconBg: iconBackgrounds[0]
  },

  // Productivity
  {
    id: 6,
    name: "QuickCapture",
    description: "Take screenshots, annotate them, and easily share or save them to your cloud storage with just one click.",
    category: "Productivity",
    rating: 4.8,
    users: 1876543,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.2.1",
    icon: Image,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 7,
    name: "TaskMaster",
    description: "Turn any webpage into a task with deadlines, reminders, and notes for better work management and productivity.",
    category: "Productivity",
    rating: 4.7,
    users: 1245789,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.5.0",
    icon: Clock,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 8,
    name: "SmartBookmark",
    description: "Advanced bookmarking with tags, collections, full-text search, and AI-powered organization of your saved pages.",
    category: "Productivity",
    rating: 4.6,
    users: 982456,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.4",
    icon: Bookmark,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 9,
    name: "WebClipper",
    description: "Save entire web pages, articles, or selected content to your note-taking app with proper formatting and organization.",
    category: "Productivity",
    rating: 4.5,
    users: 754632,
    installed: true,
    enabled: true,
    featured: false,
    version: "2.1.3",
    icon: Scissors,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 10,
    name: "FocusZone",
    description: "Block distracting websites during work hours, set productivity goals, and track your browsing habits for better focus.",
    category: "Productivity",
    rating: 4.4,
    users: 652147,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.5.2",
    icon: Lightbulb,
    iconBg: iconBackgrounds[1]
  },

  // Developer Tools
  {
    id: 11,
    name: "CodeInspector",
    description: "Advanced developer tools with enhanced debugging features, source mapping, performance analysis, and accessibility auditing.",
    category: "Developer Tools",
    rating: 4.9,
    users: 1254987,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.4.0",
    icon: Code,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 12,
    name: "GitPulse",
    description: "View GitHub repositories, pull requests, and issues directly in your browser with commit history visualization.",
    category: "Developer Tools",
    rating: 4.8,
    users: 987654,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.2.1",
    icon: Github,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 13,
    name: "JSONFormatter",
    description: "Formats and validates JSON data with syntax highlighting, collapsible trees, and search functionality for large datasets.",
    category: "Developer Tools",
    rating: 4.7,
    users: 876543,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.6.3",
    icon: FileCode,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 14,
    name: "APITester",
    description: "Create, save, and run API requests directly from your browser with response visualization and environment variables.",
    category: "Developer Tools",
    rating: 4.6,
    users: 765432,
    installed: true,
    enabled: false,
    featured: false,
    version: "2.0.5",
    icon: Send,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 15,
    name: "ResponsiveDesigner",
    description: "Test websites on multiple device sizes simultaneously with interactive viewport resizing and screenshot capabilities.",
    category: "Developer Tools",
    rating: 4.5,
    users: 654321,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.9.2",
    icon: Layers,
    iconBg: iconBackgrounds[2]
  },

  // Web3 & Crypto
  {
    id: 16,
    name: "CryptoTracker",
    description: "Real-time cryptocurrency price tracking, portfolio management, and alerts for price changes across major exchanges.",
    category: "Web3 & Crypto",
    rating: 4.8,
    users: 1345678,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.7.1",
    icon: BarChart4,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 17,
    name: "NexusWallet",
    description: "Secure cryptocurrency wallet with support for multiple blockchains, NFT display, and direct interaction with dApps.",
    category: "Web3 & Crypto",
    rating: 4.7,
    users: 952468,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.0.2",
    icon: Wallet,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 18,
    name: "GasSaver",
    description: "Monitors Ethereum gas prices to notify you when it's the best time to make transactions with minimal fees.",
    category: "Web3 & Crypto",
    rating: 4.6,
    users: 752369,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.5.4",
    icon: Zap,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 19,
    name: "DeFiDashboard",
    description: "Track your DeFi investments, yields, and liquidity pools across protocols with earnings projections and risk analysis.",
    category: "Web3 & Crypto",
    rating: 4.5,
    users: 634521,
    installed: true,
    enabled: true,
    featured: false,
    version: "2.2.0",
    icon: PieChart,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 20,
    name: "NFTExplorer",
    description: "Browse NFT collections, track floor prices, and get alerts for new drops from your favorite creators and projects.",
    category: "Web3 & Crypto",
    rating: 4.4,
    users: 521478,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.8.3",
    icon: Image,
    iconBg: iconBackgrounds[3]
  },

  // Search & Navigation
  {
    id: 21,
    name: "SuperSearch",
    description: "Enhanced search capabilities with multi-engine results, visual search history, and AI-powered search suggestions.",
    category: "Search & Navigation",
    rating: 4.7,
    users: 2154789,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.9.0",
    icon: Search,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 22,
    name: "TabMaster",
    description: "Advanced tab management with grouping, searching, vertical tabs, and session saving for better organization.",
    category: "Search & Navigation",
    rating: 4.6,
    users: 1852369,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.1.4",
    icon: Layers,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 23,
    name: "QuickJump",
    description: "Navigate websites with keyboard shortcuts, custom commands, and quick access to frequently used features.",
    category: "Search & Navigation",
    rating: 4.5,
    users: 1523698,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.7.2",
    icon: Zap,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 24,
    name: "HistoryMaster",
    description: "Enhanced browsing history with full-text search, visual timeline, and AI-categorized history entries for easy retrieval.",
    category: "Search & Navigation",
    rating: 4.4,
    users: 1254789,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.3.5",
    icon: Clock,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 25,
    name: "LinkPreview",
    description: "See rich previews of links before clicking them, including content summaries, media, and security information.",
    category: "Search & Navigation",
    rating: 4.3,
    users: 987456,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.4.1",
    icon: Link,
    iconBg: iconBackgrounds[4]
  },

  // Shopping & Finance
  {
    id: 26,
    name: "PriceSpy",
    description: "Automatically finds and applies coupon codes, tracks price history, and alerts you to price drops on products you're watching.",
    category: "Shopping & Finance",
    rating: 4.8,
    users: 1987456,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.5.2",
    icon: ShoppingBag,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 27,
    name: "BudgetGuard",
    description: "Track your online spending, set budget limits for shopping categories, and get warnings before making impulse purchases.",
    category: "Shopping & Finance",
    rating: 4.7,
    users: 1523698,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.8.0",
    icon: CreditCard,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 28,
    name: "CashbackHunter",
    description: "Automatically activates cashback opportunities when shopping online and tracks your rewards across multiple programs.",
    category: "Shopping & Finance",
    rating: 4.6,
    users: 1254789,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.9.3",
    icon: Download,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 29,
    name: "InvoiceMaster",
    description: "Automatically captures and organizes receipts and invoices from your online purchases for expense tracking and taxes.",
    category: "Shopping & Finance",
    rating: 4.5,
    users: 982456,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.1.4",
    icon: FileText,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 30,
    name: "StockRadar",
    description: "Track stock prices, get real-time market alerts, and access financial news and earnings reports directly in your browser.",
    category: "Shopping & Finance",
    rating: 4.4,
    users: 856321,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.6.2",
    icon: BarChart4,
    iconBg: iconBackgrounds[5]
  },

  // Communication & Social
  {
    id: 31,
    name: "MailAssistant",
    description: "Smart email notifications, scheduling, templates, and tracking for Gmail and other webmail services with AI response suggestions.",
    category: "Communication & Social",
    rating: 4.7,
    users: 1654321,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.6.5",
    icon: Mail,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 32,
    name: "SocialScheduler",
    description: "Schedule and post to multiple social media platforms directly from your browser with analytics and content suggestions.",
    category: "Communication & Social",
    rating: 4.6,
    users: 1456789,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.0.1",
    icon: Share2,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 33,
    name: "MeetingManager",
    description: "Video meeting enhancements with automatic note-taking, recording, transcription, and calendar integration.",
    category: "Communication & Social",
    rating: 4.5,
    users: 1234567,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.4",
    icon: UserRound,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 34,
    name: "NotificationCenter",
    description: "Centralized notification management for all your web apps and services with custom filters and scheduled quiet hours.",
    category: "Communication & Social",
    rating: 4.4,
    users: 987654,
    installed: true,
    enabled: false,
    featured: false,
    version: "2.3.2",
    icon: BellRing,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 35,
    name: "TranslateNow",
    description: "Instant webpage translation with support for 100+ languages, including offline mode and specialized terminology.",
    category: "Communication & Social",
    rating: 4.3,
    users: 852147,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.5.7",
    icon: Languages,
    iconBg: iconBackgrounds[6]
  },

  // Media & Entertainment
  {
    id: 36,
    name: "MediaMaster",
    description: "Enhanced video controls, picture-in-picture, audio extraction, and customizable playback speeds for streaming platforms.",
    category: "Media & Entertainment",
    rating: 4.8,
    users: 2345678,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.7.2",
    icon: Sparkles,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 37,
    name: "NoiseControl",
    description: "Audio equalizer, volume boosting, and background noise suppression for better sound quality in videos and music.",
    category: "Media & Entertainment",
    rating: 4.7,
    users: 1987654,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.9.5",
    icon: VolumeX,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 38,
    name: "DarkReader+",
    description: "Advanced dark mode with customizable themes, scheduled activation, and per-site settings for better nighttime browsing.",
    category: "Media & Entertainment",
    rating: 4.6,
    users: 1765432,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.9.8",
    icon: Sunrise,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 39,
    name: "NewsDigest",
    description: "Personalized news feed that aggregates content from multiple sources with AI summaries and fact-checking indicators.",
    category: "Media & Entertainment",
    rating: 4.5,
    users: 1452369,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.4.3",
    icon: Newspaper,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 40,
    name: "WeatherNow",
    description: "Real-time weather information with forecasts, radar, and severe weather alerts based on your current location.",
    category: "Media & Entertainment",
    rating: 4.4,
    users: 1236547,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.7.6",
    icon: CloudRain,
    iconBg: iconBackgrounds[7]
  },
];
