import { 
  Shield, 
  Lock, 
  Search, 
  Download, 
  Zap, 
  Eye, 
  Code, 
  FileCode, 
  UserRound, 
  Clock, 
  CreditCard, 
  Bookmark,
  Image, 
  Send, 
  Mail, 
  Layers, 
  PieChart, 
  Languages, 
  Scissors,
  VolumeX, 
  Lightbulb, 
  Sparkles, 
  Github, 
  CloudRain, 
  Newspaper,
  FileText, 
  Sunrise, 
  ShoppingBag, 
  Wallet, 
  BellRing, 
  Link,
  Fingerprint, 
  BarChart4, 
  Share2, 
  Settings, 
  KeyRound, 
  LucideIcon,
  MessageSquare, 
  Search as SearchIcon, 
  BarChart, 
  Gamepad,
  Calculator,
  Coins,
  BadgeDollarSign,
  Receipt,
  PiggyBank,
  LineChart,
  TrendingUp,
  Pencil,
  Landmark,
  Banknote,
  Activity,
  Heart,
  Dumbbell,
  PersonStanding, // Replacing Running with PersonStanding
  Timer,
  Apple,
  Scale,
  Bed,
  Baby,
  Pill,
  UtensilsCrossed,
  Salad,
  ScrollText,
  Coffee,
  Beef,
  GlassWater,
  Medal,
  Egg,
  Globe,
  Database
} from "lucide-react";

export interface Extension {
  id: number;
  name: string;
  description: string;
  category: string;
  rating: number;
  users: number;
  installed: boolean;
  enabled: boolean;
  featured: boolean;
  version: string;
  icon: LucideIcon;
  iconBg: string;
  isBeta?: boolean;
  estimatedRelease?: string;
}

const iconBackgrounds = [
  "bg-gradient-to-br from-purple-500 to-purple-700",
  "bg-gradient-to-br from-blue-500 to-blue-700",
  "bg-gradient-to-br from-pink-500 to-pink-700",
  "bg-gradient-to-br from-emerald-500 to-emerald-700",
  "bg-gradient-to-br from-amber-500 to-amber-700",
  "bg-gradient-to-br from-sky-500 to-sky-700",
  "bg-gradient-to-br from-rose-500 to-rose-700",
  "bg-gradient-to-br from-indigo-500 to-indigo-700",
  "bg-gradient-to-br from-green-500 to-green-700",
  "bg-gradient-to-br from-orange-500 to-orange-700",
  "bg-gradient-to-br from-red-500 to-red-700",
];

export const extensionsData: Extension[] = [
  // Privacy & Security
  {
    id: 1,
    name: "NexusShield",
    description: "Comprehensive ad blocker and privacy protector that blocks trackers, cookies, and unwanted ads across all websites.",
    category: "Privacy & Security",
    rating: 4.9,
    users: 2547823,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.3.1",
    icon: Shield,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 2,
    name: "PrivatePass",
    description: "Advanced password manager that securely stores your passwords with military-grade encryption and auto-fills login forms.",
    category: "Privacy & Security",
    rating: 4.8,
    users: 1824596,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.1.0",
    icon: Lock,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 3,
    name: "ThreatDefender",
    description: "Detects and blocks malicious websites, phishing attempts, and potentially harmful downloads in real-time.",
    category: "Privacy & Security",
    rating: 4.7,
    users: 965321,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.9.2",
    icon: Shield,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 4,
    name: "BiometricGuard",
    description: "Adds fingerprint and facial recognition support for website logins, enhancing security while simplifying the authentication process.",
    category: "Privacy & Security",
    rating: 4.6,
    users: 542987,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.0.5",
    icon: Fingerprint,
    iconBg: iconBackgrounds[0]
  },
  {
    id: 5,
    name: "DataVault",
    description: "Local encryption for sensitive information like credit cards and personal data with secure access via master password.",
    category: "Privacy & Security",
    rating: 4.5,
    users: 387451,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.7.3",
    icon: KeyRound,
    iconBg: iconBackgrounds[0]
  },

  // Productivity
  {
    id: 6,
    name: "QuickCapture",
    description: "Take screenshots, annotate them, and easily share or save them to your cloud storage with just one click.",
    category: "Productivity",
    rating: 4.8,
    users: 1876543,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.2.1",
    icon: Image,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 7,
    name: "TaskMaster",
    description: "Turn any webpage into a task with deadlines, reminders, and notes for better work management and productivity.",
    category: "Productivity",
    rating: 4.7,
    users: 1245789,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.5.0",
    icon: Clock,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 8,
    name: "SmartBookmark",
    description: "Advanced bookmarking with tags, collections, full-text search, and AI-powered organization of your saved pages.",
    category: "Productivity",
    rating: 4.6,
    users: 982456,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.4",
    icon: Bookmark,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 9,
    name: "WebClipper",
    description: "Save entire web pages, articles, or selected content to your note-taking app with proper formatting and organization.",
    category: "Productivity",
    rating: 4.5,
    users: 754632,
    installed: true,
    enabled: true,
    featured: false,
    version: "2.1.3",
    icon: Scissors,
    iconBg: iconBackgrounds[1]
  },
  {
    id: 10,
    name: "FocusZone",
    description: "Block distracting websites during work hours, set productivity goals, and track your browsing habits for better focus.",
    category: "Productivity",
    rating: 4.4,
    users: 652147,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.5.2",
    icon: Lightbulb,
    iconBg: iconBackgrounds[1]
  },

  // Developer Tools
  {
    id: 11,
    name: "CodeInspector",
    description: "Advanced developer tools with enhanced debugging features, source mapping, performance analysis, and accessibility auditing.",
    category: "Developer Tools",
    rating: 4.9,
    users: 1254987,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.4.0",
    icon: Code,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 12,
    name: "GitPulse",
    description: "View GitHub repositories, pull requests, and issues directly in your browser with commit history visualization.",
    category: "Developer Tools",
    rating: 4.8,
    users: 987654,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.2.1",
    icon: Github,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 13,
    name: "JSONFormatter",
    description: "Formats and validates JSON data with syntax highlighting, collapsible trees, and search functionality for large datasets.",
    category: "Developer Tools",
    rating: 4.7,
    users: 876543,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.6.3",
    icon: FileCode,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 14,
    name: "APITester",
    description: "Create, save, and run API requests directly from your browser with response visualization and environment variables.",
    category: "Developer Tools",
    rating: 4.6,
    users: 765432,
    installed: true,
    enabled: false,
    featured: false,
    version: "2.0.5",
    icon: Send,
    iconBg: iconBackgrounds[2]
  },
  {
    id: 15,
    name: "ResponsiveDesigner",
    description: "Test websites on multiple device sizes simultaneously with interactive viewport resizing and screenshot capabilities.",
    category: "Developer Tools",
    rating: 4.5,
    users: 654321,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.9.2",
    icon: Layers,
    iconBg: iconBackgrounds[2]
  },

  // Web3 & Crypto
  {
    id: 16,
    name: "CryptoTracker",
    description: "Real-time cryptocurrency price tracking, portfolio management, and alerts for price changes across major exchanges.",
    category: "Web3 & Crypto",
    rating: 4.8,
    users: 1345678,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.7.1",
    icon: BarChart4,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 17,
    name: "NexusWallet",
    description: "Secure cryptocurrency wallet with support for multiple blockchains, NFT display, and direct interaction with dApps.",
    category: "Web3 & Crypto",
    rating: 4.7,
    users: 952468,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.0.2",
    icon: Wallet,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 18,
    name: "GasSaver",
    description: "Monitors Ethereum gas prices to notify you when it's the best time to make transactions with minimal fees.",
    category: "Web3 & Crypto",
    rating: 4.6,
    users: 752369,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.5.4",
    icon: Zap,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 19,
    name: "DeFiDashboard",
    description: "Track your DeFi investments, yields, and liquidity pools across protocols with earnings projections and risk analysis.",
    category: "Web3 & Crypto",
    rating: 4.5,
    users: 634521,
    installed: true,
    enabled: true,
    featured: false,
    version: "2.2.0",
    icon: PieChart,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 20,
    name: "NFTExplorer",
    description: "Browse NFT collections, track floor prices, and get alerts for new drops from your favorite creators and projects.",
    category: "Web3 & Crypto",
    rating: 4.4,
    users: 521478,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.8.3",
    icon: Image,
    iconBg: iconBackgrounds[3]
  },

  // Search - renamed from "Search & Navigation"
  {
    id: 21,
    name: "SuperSearch",
    description: "Enhanced search capabilities with multi-engine results, visual search history, and AI-powered search suggestions.",
    category: "Search",
    rating: 4.7,
    users: 2154789,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.9.0",
    icon: Search,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 22,
    name: "TabMaster",
    description: "Advanced tab management with grouping, searching, vertical tabs, and session saving for better organization.",
    category: "Search",
    rating: 4.6,
    users: 1852369,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.1.4",
    icon: Layers,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 23,
    name: "QuickJump",
    description: "Navigate websites with keyboard shortcuts, custom commands, and quick access to frequently used features.",
    category: "Search",
    rating: 4.5,
    users: 1523698,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.7.2",
    icon: Zap,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 24,
    name: "HistoryMaster",
    description: "Enhanced browsing history with full-text search, visual timeline, and AI-categorized history entries for easy retrieval.",
    category: "Search",
    rating: 4.4,
    users: 1254789,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.3.5",
    icon: Clock,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 25,
    name: "LinkPreview",
    description: "See rich previews of links before clicking them, including content summaries, media, and security information.",
    category: "Search",
    rating: 4.3,
    users: 987456,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.4.1",
    icon: Link,
    iconBg: iconBackgrounds[4]
  },

  // Shopping - Split from "Shopping & Finance"
  {
    id: 26,
    name: "PriceSpy",
    description: "Automatically finds and applies coupon codes, tracks price history, and alerts you to price drops on products you're watching.",
    category: "Shopping",
    rating: 4.8,
    users: 1987456,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.5.2",
    icon: ShoppingBag,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 28,
    name: "CashbackHunter",
    description: "Automatically activates cashback opportunities when shopping online and tracks your rewards across multiple programs.",
    category: "Shopping",
    rating: 4.6,
    users: 1254789,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.9.3",
    icon: Download,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 29,
    name: "InvoiceMaster",
    description: "Automatically captures and organizes receipts and invoices from your online purchases for expense tracking and taxes.",
    category: "Shopping",
    rating: 4.5,
    users: 982456,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.1.4",
    icon: FileText,
    iconBg: iconBackgrounds[5]
  },

  // Finance - Split from "Shopping & Finance"
  {
    id: 27,
    name: "BudgetGuard",
    description: "Track your online spending, set budget limits for shopping categories, and get warnings before making impulse purchases.",
    category: "Finance",
    rating: 4.7,
    users: 1523698,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.8.0",
    icon: CreditCard,
    iconBg: iconBackgrounds[9]
  },
  {
    id: 30,
    name: "StockRadar",
    description: "Track stock prices, get real-time market alerts, and access financial news and earnings reports directly in your browser.",
    category: "Finance",
    rating: 4.4,
    users: 856321,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.6.2",
    icon: BarChart4,
    iconBg: iconBackgrounds[9]
  },
  {
    id: 72,
    name: "LoanCalculator",
    description: "Calculate loan payments, interest rates, and amortization schedules for mortgages, auto loans, and personal financing options.",
    category: "Finance",
    rating: 4.5,
    users: 654321,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.2.7",
    icon: Calculator,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 73,
    name: "SubscriptionManager",
    description: "Track all your subscriptions in one place with renewal alerts, spending analysis, and suggestions for potential cost savings.",
    category: "Finance",
    rating: 4.5,
    users: 547891,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.2",
    icon: CreditCard,
    iconBg: iconBackgrounds[5]
  },
  {
    id: 75,
    name: "FinancialAdvisor",
    description: "AI-powered financial advisory with personalized recommendations for investing, saving, debt management, and retirement planning.",
    category: "Finance",
    rating: 4.3,
    users: 325698,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.0.4",
    icon: Landmark,
    iconBg: iconBackgrounds[5]
  },

  // Communication
  {
    id: 31,
    name: "MailAssistant",
    description: "Smart email notifications, scheduling, templates, and tracking for Gmail and other webmail services with AI response suggestions.",
    category: "Communication",
    rating: 4.7,
    users: 1654321,
    installed: true,
    enabled: true,
    featured: true,
    version: "2.6.5",
    icon: Mail,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 32,
    name: "MeetingManager",
    description: "Video meeting enhancements with automatic note-taking, recording, transcription, and calendar integration.",
    category: "Communication",
    rating: 4.5,
    users: 1234567,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.4",
    icon: UserRound,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 33,
    name: "NotificationCenter",
    description: "Centralized notification management for all your web apps and services with custom filters and scheduled quiet hours.",
    category: "Communication",
    rating: 4.4,
    users: 987654,
    installed: true,
    enabled: false,
    featured: false,
    version: "2.3.2",
    icon: BellRing,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 34,
    name: "TranslateNow",
    description: "Instant webpage translation with support for 100+ languages, including offline mode and specialized terminology.",
    category: "Communication",
    rating: 4.3,
    users: 852147,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.5.7",
    icon: Languages,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 35,
    name: "ChatConnect",
    description: "Universal chat platform that connects all your messaging apps into one unified inbox with smart filtering and priority sorting.",
    category: "Communication",
    rating: 4.6,
    users: 1123456,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.4.1",
    icon: MessageSquare,
    iconBg: iconBackgrounds[6]
  },

  // Social
  {
    id: 36,
    name: "SocialScheduler",
    description: "Schedule and post to multiple social media platforms directly from your browser with analytics and content suggestions.",
    category: "Social",
    rating: 4.6,
    users: 1456789,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.0.1",
    icon: Share2,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 37,
    name: "InfluenceTracker",
    description: "Track your social media growth, engagement metrics, and audience demographics across all major platforms.",
    category: "Social",
    rating: 4.5,
    users: 892345,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.7.3",
    icon: BarChart4,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 38,
    name: "ContentCalendar",
    description: "Visual calendar for planning and organizing social media content with team collaboration and approval workflows.",
    category: "Social",
    rating: 4.4,
    users: 743218,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.9.5",
    icon: Clock,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 39,
    name: "TrendAlert",
    description: "Get real-time alerts about trending topics and viral content relevant to your interests or business niche.",
    category: "Social",
    rating: 4.3,
    users: 654987,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.2.7",
    icon: Lightbulb,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 40,
    name: "ProfileOptimizer",
    description: "Optimize your social media profiles with AI-powered suggestions for better visibility and engagement.",
    category: "Social",
    rating: 4.2,
    users: 524863,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.6.4",
    icon: UserRound,
    iconBg: iconBackgrounds[7]
  },

  // Media
  {
    id: 36,
    name: "MediaMaster",
    description: "Enhanced video controls, picture-in-picture, audio extraction, and customizable playback speeds for streaming platforms.",
    category: "Media",
    rating: 4.8,
    users: 2345678,
    installed: true,
    enabled: true,
    featured: true,
    version: "3.7.2",
    icon: Sparkles,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 37,
    name: "NoiseControl",
    description: "Audio equalizer, volume boosting, and background noise suppression for better sound quality in videos and music.",
    category: "Media",
    rating: 4.7,
    users: 1987654,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.9.5",
    icon: VolumeX,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 38,
    name: "DarkReader+",
    description: "Advanced dark mode with customizable themes, scheduled activation, and per-site settings for better nighttime browsing.",
    category: "Media",
    rating: 4.6,
    users: 1765432,
    installed: true,
    enabled: true,
    featured: false,
    version: "1.9.8",
    icon: Sunrise,
    iconBg: iconBackgrounds[7]
  },
  
  // Entertainment
  {
    id: 39,
    name: "NewsDigest",
    description: "Personalized news feed that aggregates content from multiple sources with AI summaries and fact-checking indicators.",
    category: "Entertainment",
    rating: 4.5,
    users: 1452369,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.4.3",
    icon: Newspaper,
    iconBg: iconBackgrounds[7]
  },
  {
    id: 40,
    name: "WeatherNow",
    description: "Real-time weather information with forecasts, radar, and severe weather alerts based on your current location.",
    category: "Entertainment",
    rating: 4.4,
    users: 1236547,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.7.6",
    icon: CloudRain,
    iconBg: iconBackgrounds[7]
  },

  // Analytics
  {
    id: 51,
    name: "TrafficInsight",
    description: "Comprehensive website analytics with visitor tracking, heatmaps, conversion funnels, and detailed reporting dashboards.",
    category: "Analytics",
    rating: 4.8,
    users: 1456789,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.2.5",
    icon: BarChart,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 52,
    name: "EventTracker",
    description: "Track user interactions and custom events on your website with real-time analytics and behavior flow visualization.",
    category: "Analytics",
    rating: 4.7,
    users: 987456,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.8.3",
    icon: PieChart,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 53,
    name: "CompetitorMonitor",
    description: "Benchmark your website's performance against competitors with side-by-side analytics and traffic comparison reports.",
    category: "Analytics",
    rating: 4.6,
    users: 762345,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.1.7",
    icon: BarChart4,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 54,
    name: "ConversionOptimizer",
    description: "A/B testing tool for optimizing landing pages, forms, and checkout processes with statistical significance reporting.",
    category: "Analytics",
    rating: 4.7,
    users: 654987,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.5.2",
    icon: BarChart,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 55,
    name: "UserJourney",
    description: "Visualize and analyze customer journeys across your website with path analysis, drop-off points, and improvement suggestions.",
    category: "Analytics",
    rating: 4.5,
    users: 543876,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.9.4",
    icon: PieChart,
    iconBg: iconBackgrounds[8]
  },

  // SEO
  {
    id: 56,
    name: "SEOAudit",
    description: "Comprehensive SEO audit tool that analyzes your website and provides actionable recommendations for better search rankings.",
    category: "SEO",
    rating: 4.9,
    users: 1345678,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.5.1",
    icon: SearchIcon,
    iconBg: iconBackgrounds[9]
  },
  {
    id: 57,
    name: "KeywordTracker",
    description: "Monitor your keyword rankings across search engines and track improvements over time with competitor comparison.",
    category: "SEO",
    rating: 4.7,
    users: 876543,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.6.3",
    icon: SearchIcon,
    iconBg: iconBackgrounds[9]
  },
  {
    id: 58,
    name: "BacklinkAnalyzer",
    description: "Discover and monitor backlinks pointing to your website with quality assessment and opportunity identification.",
    category: "SEO",
    rating: 4.6,
    users: 765432,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.2.5",
    icon: Link,
    iconBg: iconBackgrounds[9]
  },
  {
    id: 59,
    name: "ContentOptimizer",
    description: "Analyze and optimize your content for search engines with keyword suggestions, readability checks, and on-page SEO factors.",
    category: "SEO",
    rating: 4.8,
    users: 654321,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.9.7",
    icon: FileText,
    iconBg: iconBackgrounds[9]
  },
  {
    id: 60,
    name: "LocalSEOBooster",
    description: "Improve your local search presence with business listing management, review monitoring, and local keyword optimization.",
    category: "SEO",
    rating: 4.5,
    users: 543210,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.4",
    icon: SearchIcon,
    iconBg: iconBackgrounds[9]
  },

  // Gaming
  {
    id: 61,
    name: "GameBooster",
    description: "Optimize your system for gaming with automatic resource allocation, background process management, and performance monitoring.",
    category: "Gaming",
    rating: 4.9,
    users: 2345678,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.7.2",
    icon: Gamepad,
    iconBg: iconBackgrounds[10]
  },
  {
    id: 62,
    name: "StreamOverlay",
    description: "Customizable overlay for game streaming with viewer interactions, alerts, chat integration, and performance stats.",
    category: "Gaming",
    rating: 4.8,
    users: 1876543,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.8.5",
    icon: Gamepad,
    iconBg: iconBackgrounds[10]
  },
  {
    id: 63,
    name: "GameDeals",
    description: "Find the best deals on games across multiple platforms with price history tracking, wish list notifications, and discount alerts.",
    category: "Gaming",
    rating: 4.7,
    users: 1654321,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.4.3",
    icon: ShoppingBag,
    iconBg: iconBackgrounds[10]
  },
  {
    id: 64,
    name: "AchievementTracker",
    description: "Track your gaming achievements and progress across multiple gaming platforms in one unified dashboard.",
    category: "Gaming",
    rating: 4.6,
    users: 1432567,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.1.9",
    icon: Gamepad,
    iconBg: iconBackgrounds[10]
  },
  {
    id: 65,
    name: "GameCommunity",
    description: "Connect with fellow gamers, join communities, and schedule gaming sessions with friends across different platforms.",
    category: "Gaming",
    rating: 4.5,
    users: 1234567,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.9.6",
    icon: UserRound,
    iconBg: iconBackgrounds[10]
  },

  // Health & Fitness
  {
    id: 76,
    name: "WorkoutTracker",
    description: "Log and analyze your workouts with detailed exercise tracking, personal records, and progress visualization over time.",
    category: "Health & Fitness",
    rating: 4.9,
    users: 1754289,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.5.2",
    icon: Dumbbell,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 77,
    name: "HeartRateMonitor",
    description: "Track your heart rate patterns during activities, rest periods, and sleep with detailed analytics and health insights.",
    category: "Health & Fitness",
    rating: 4.8,
    users: 1623547,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.4.8",
    icon: Heart,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 78,
    name: "RunTracker",
    description: "GPS running tracker with route mapping, pace analysis, interval training support, and community challenges.",
    category: "Health & Fitness",
    rating: 4.8,
    users: 1425698,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.2.7",
    icon: PersonStanding, // Changed from Running to PersonStanding
    iconBg: iconBackgrounds[6]
  },
  {
    id: 79,
    name: "FitnessScheduler",
    description: "Plan and schedule your workouts with customizable routines, rest day reminders, and integration with your calendar.",
    category: "Health & Fitness",
    rating: 4.7,
    users: 1098765,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.1.5",
    icon: Clock,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 80,
    name: "StepCounter",
    description: "Daily step tracking with personalized goals, activity streaks, and walking route suggestions based on your location.",
    category: "Health & Fitness",
    rating: 4.7,
    users: 976543,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.9.4",
    icon: Activity,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 81,
    name: "SleepAnalyzer",
    description: "Monitor sleep patterns, quality, and duration with suggestions for improving your sleep cycle and restfulness.",
    category: "Health & Fitness",
    rating: 4.6,
    users: 854321,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.7.1",
    icon: Bed,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 82,
    name: "MeditationGuide",
    description: "Guided meditation sessions with breathing exercises, focus training, and stress reduction techniques for mental wellness.",
    category: "Health & Fitness",
    rating: 4.6,
    users: 743219,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.0.6",
    icon: Sparkles,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 83,
    name: "WeightTracker",
    description: "Record and visualize weight changes with trend analysis, goal setting, and body composition tracking tools.",
    category: "Health & Fitness",
    rating: 4.5,
    users: 632587,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.4.3",
    icon: Scale,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 84,
    name: "IntervalTimer",
    description: "Customizable interval timer for HIIT workouts, Pomodoro technique, and other timed training methods with audio cues.",
    category: "Health & Fitness",
    rating: 4.5,
    users: 528746,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.7",
    icon: Timer,
    iconBg: iconBackgrounds[6]
  },
  {
    id: 85,
    name: "RecoveryAssistant",
    description: "Personalized recovery recommendations based on workout intensity, including stretching routines and mobility exercises.",
    category: "Health & Fitness",
    rating: 4.4,
    users: 412537,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.2.8",
    icon: Heart,
    iconBg: iconBackgrounds[6]
  },

  // Nutrition
  {
    id: 86,
    name: "MealPlanner",
    description: "Create personalized meal plans with nutrition tracking, grocery lists, and recipe suggestions based on your dietary preferences.",
    category: "Nutrition",
    rating: 4.9,
    users: 1876543,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.4.2",
    icon: UtensilsCrossed,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 87,
    name: "NutrientTracker",
    description: "Detailed nutrition tracking with macronutrient ratios, micronutrient analysis, and personalized intake recommendations.",
    category: "Nutrition",
    rating: 4.8,
    users: 1654321,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.6.5",
    icon: Apple,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 88,
    name: "RecipeFinder",
    description: "Discover recipes based on ingredients you already have, dietary restrictions, and nutritional goals with step-by-step instructions.",
    category: "Nutrition",
    rating: 4.8,
    users: 1543219,
    installed: false,
    enabled: false,
    featured: false,
    version: "3.1.7",
    icon: ScrollText,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 89,
    name: "WaterReminder",
    description: "Stay hydrated with personalized water intake goals, reminders throughout the day, and hydration tracking analytics.",
    category: "Nutrition",
    rating: 4.7,
    users: 1432187,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.3.4",
    icon: GlassWater,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 90,
    name: "AllergenDetector",
    description: "Scan food products to detect allergens, additives, and ingredients that don't match your dietary requirements or restrictions.",
    category: "Nutrition",
    rating: 4.7,
    users: 1321098,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.8.1",
    icon: Eye,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 91,
    name: "CalorieCalculator",
    description: "Calculate and track daily calorie needs based on your age, activity level, goals, and metabolic factors.",
    category: "Nutrition",
    rating: 4.6,
    users: 1209876,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.9.5",
    icon: Calculator,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 92,
    name: "MealTimer",
    description: "Optimize meal timing for metabolism, energy levels, and health with personalized eating schedule recommendations.",
    category: "Nutrition",
    rating: 4.6,
    users: 1098765,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.5.3",
    icon: Clock,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 93,
    name: "ProteinOptimizer",
    description: "Track and optimize protein intake for fitness goals, muscle recovery, and overall health with food recommendations.",
    category: "Nutrition",
    rating: 4.5,
    users: 987654,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.0.7",
    icon: Beef,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 94,
    name: "SupplementTracker",
    description: "Manage supplement schedules, track effectiveness, and receive reminders for optimal timing and combinations.",
    category: "Nutrition",
    rating: 4.5,
    users: 876543,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.7.4",
    icon: Pill,
    iconBg: iconBackgrounds[4]
  },
  {
    id: 95,
    name: "FoodJournal",
    description: "Comprehensive food diary with mood tracking, symptom monitoring, and insights into how different foods affect your wellbeing.",
    category: "Nutrition",
    rating: 4.4,
    users: 765432,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.4.6",
    icon: Salad,
    iconBg: iconBackgrounds[4]
  },

  // Web3 Explorers - New Category
  {
    id: 120,
    name: "BlockExplorer",
    description: "Comprehensive blockchain explorer for multiple networks with transaction history, smart contract analysis, and address tracking.",
    category: "Web3 Explorers",
    rating: 4.9,
    users: 1123456,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.2.1",
    icon: Database,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 121,
    name: "TokenScanner",
    description: "Advanced token explorer with price charts, holder statistics, and detailed tokenomics analysis across multiple blockchains.",
    category: "Web3 Explorers",
    rating: 4.8,
    users: 986532,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.4.5",
    icon: Eye,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 122,
    name: "DAppNavigator",
    description: "Discover and interact with decentralized applications across various blockchain ecosystems with ratings and security analysis.",
    category: "Web3 Explorers",
    rating: 4.7,
    users: 845217,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.8.3",
    icon: Globe,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 123,
    name: "TransactionTracker",
    description: "Real-time transaction monitoring across multiple blockchains with alerts, gas optimization, and detailed transaction breakdown.",
    category: "Web3 Explorers",
    rating: 4.7,
    users: 734218,
    installed: false,
    enabled: false,
    featured: true,
    version: "2.7.2",
    icon: Search,
    iconBg: iconBackgrounds[3]
  },
  {
    id: 124,
    name: "NetworkMonitor",
    description: "Monitor blockchain network health, gas prices, congestion levels, and validator performance across multiple networks.",
    category: "Web3 Explorers",
    rating: 4.6,
    users: 625431,
    installed: false,
    enabled: false,
    featured: false,
    version: "1.5.7",
    icon: Activity,
    iconBg: iconBackgrounds[3]
  },

  // News & Intelligence - New Category
  {
    id: 130,
    name: "CryptoInsights",
    description: "AI-powered crypto market intelligence with sentiment analysis, news aggregation, and predictive trend forecasting.",
    category: "News & Intelligence",
    rating: 4.9,
    users: 1345789,
    installed: false,
    enabled: false,
    featured: true,
    version: "3.5.2",
    icon: Lightbulb,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 131,
    name: "MarketPulse",
    description: "Real-time market updates, breaking news alerts, and personalized content feeds from trusted crypto and Web3 sources.",
    category: "News & Intelligence",
    rating: 4.8,
    users: 1123654,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.8.4",
    icon: Newspaper,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 132,
    name: "OnchainAnalyst",
    description: "Advanced on-chain data analysis with whale movement tracking, liquidity flow visualization, and smart money indicators.",
    category: "News & Intelligence",
    rating: 4.8,
    users: 987654,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.3.6",
    icon: BarChart,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 133,
    name: "TokenPulse",
    description: "Comprehensive token research platform with fundamental analysis, development activity tracking, and community metrics.",
    category: "News & Intelligence",
    rating: 4.7,
    users: 876543,
    installed: false,
    enabled: false,
    featured: true,
    version: "1.9.5",
    icon: PieChart,
    iconBg: iconBackgrounds[8]
  },
  {
    id: 134,
    name: "TrendRadar",
    description: "Discover emerging trends in Web3, DeFi, and NFTs before they go mainstream with social sentiment and developer activity analysis.",
    category: "News & Intelligence",
    rating: 4.6,
    users: 765432,
    installed: false,
    enabled: false,
    featured: false,
    version: "2.1.7",
    icon: TrendingUp,
    iconBg: iconBackgrounds[8]
  },
];
