// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuwlbplmztpoieoojqkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1d2xicGxtenRwb2llb29qcWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjgyOTIsImV4cCI6MjA2MjIwNDI5Mn0.JMpZQxmEQwKiQQzWIwN2uM82ZHA6WHyx_5hDYgwK91o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);